hostname = api.m.jd.com, trade-acs.m.taobao.com

^https?:\/\/api\.m\.jd\.com\/client\.action\?functionId=(wareBusiness|serverConfig|basicConfig) url script-response-body https://raw.githubusercontent.com/zhiyulabb/jev-deal-qx/main/jev_deal.js
^https?:\/\/trade-acs\.m\.taobao\.com\/gw\/mtop\.taobao\.detail\.getdetail url script-response-body https://raw.githubusercontent.com/zhiyulabb/jev-deal-qx/main/jev_deal.js
